CREATE TABLE tt_content (
    tx_wsbootstrapcomponents_accordioncontent_parent int(11) unsigned DEFAULT '0' NOT NULL,
    tx_wsbootstrapcomponents_accordion int(11) unsigned DEFAULT '0' NOT NULL,
    tx_wsbootstrapcomponents_cardbuttonlink tinytext,
    tx_wsbootstrapcomponents_cardbuttontext tinytext,
    tx_wsbootstrapcomponents_carddeck int(11) unsigned DEFAULT '0' NOT NULL,
    tx_wsbootstrapcomponents_cardfax tinytext,
    tx_wsbootstrapcomponents_cardfooter tinytext,
    tx_wsbootstrapcomponents_cardheader tinytext,
    tx_wsbootstrapcomponents_cardimage int(11) unsigned DEFAULT '0' NOT NULL,
    tx_wsbootstrapcomponents_cardimagebottom int(11) unsigned DEFAULT '0' NOT NULL,
    tx_wsbootstrapcomponents_cardmail tinytext,
    tx_wsbootstrapcomponents_cardphone tinytext,
    tx_wsbootstrapcomponents_cardsubtitle tinytext,
    tx_wsbootstrapcomponents_cardtitle tinytext,
    tx_wsbootstrapcomponents_carousel int(11) unsigned DEFAULT '0' NOT NULL,
    tx_wsbootstrapcomponents_carouselcontrols int(11) DEFAULT '0' NOT NULL,
    tx_wsbootstrapcomponents_carouselindicators int(11) DEFAULT '0' NOT NULL,
    tx_wsbootstrapcomponents_carouselintervall tinytext,
    tx_wsbootstrapcomponents_carouselpause tinytext,
    tx_wsbootstrapcomponents_jumbotronfull int(11) DEFAULT '0' NOT NULL,
    tx_wsbootstrapcomponents_jumbotronlink tinytext,
    tx_wsbootstrapcomponents_jumbotronlinktext tinytext,
    tx_wsbootstrapcomponents_jumbotrontext tinytext,
    tx_wsbootstrapcomponents_jumbotrontexttwo tinytext,
    tx_wsbootstrapcomponents_modal tinytext,
    tx_wsbootstrapcomponents_modalaction tinytext,
    tx_wsbootstrapcomponents_modalactiontext tinytext,
    tx_wsbootstrapcomponents_modalclose tinytext,
    tx_wsbootstrapcomponents_modalcontent int(11) unsigned DEFAULT '0' NOT NULL,
    tx_wsbootstrapcomponents_modalcontent_parent int(11) unsigned DEFAULT '0' NOT NULL
);
CREATE TABLE tx_wsbootstrapcomponents_accordion (
    uid int(11) NOT NULL auto_increment,
    pid int(11) DEFAULT '0' NOT NULL,
    parentid int(11) DEFAULT '0' NOT NULL,
    parenttable varchar(255) DEFAULT '' NOT NULL,
    sorting int(11) unsigned DEFAULT '0' NOT NULL,
    t3ver_oid int(11) unsigned DEFAULT '0' NOT NULL,
    t3ver_id int(11) DEFAULT '0' NOT NULL,
    t3ver_wsid int(11) DEFAULT '0' NOT NULL,
    t3ver_label varchar(255) DEFAULT '' NOT NULL,
    t3ver_state tinyint(4) DEFAULT '0' NOT NULL,
    t3ver_stage int(11) DEFAULT '0' NOT NULL,
    t3ver_count int(11) DEFAULT '0' NOT NULL,
    t3ver_tstamp int(11) DEFAULT '0' NOT NULL,
    t3ver_move_id int(11) DEFAULT '0' NOT NULL,
    tstamp int(11) unsigned DEFAULT '0' NOT NULL,
    crdate int(11) unsigned DEFAULT '0' NOT NULL,
    cruser_id int(11) unsigned DEFAULT '0' NOT NULL,
    deleted tinyint(4) unsigned DEFAULT '0' NOT NULL,
    hidden tinyint(4) unsigned DEFAULT '0' NOT NULL,
    starttime int(11) unsigned DEFAULT '0' NOT NULL,
    endtime int(11) unsigned DEFAULT '0' NOT NULL,
    sys_language_uid int(11) DEFAULT '0' NOT NULL,
    l10n_parent int(11) unsigned DEFAULT '0' NOT NULL,
    l10n_diffsource mediumblob,
    tx_wsbootstrapcomponents_accordionheader tinytext,
    tx_wsbootstrapcomponents_accordioncontent int(11) unsigned DEFAULT '0' NOT NULL,
    PRIMARY KEY (uid),
    KEY parent (pid),
    KEY t3ver_oid (t3ver_oid,t3ver_wsid),
    KEY language (l10n_parent,sys_language_uid)
);
CREATE TABLE tx_wsbootstrapcomponents_carddeck (
    uid int(11) NOT NULL auto_increment,
    pid int(11) DEFAULT '0' NOT NULL,
    parentid int(11) DEFAULT '0' NOT NULL,
    parenttable varchar(255) DEFAULT '' NOT NULL,
    sorting int(11) unsigned DEFAULT '0' NOT NULL,
    t3ver_oid int(11) unsigned DEFAULT '0' NOT NULL,
    t3ver_id int(11) DEFAULT '0' NOT NULL,
    t3ver_wsid int(11) DEFAULT '0' NOT NULL,
    t3ver_label varchar(255) DEFAULT '' NOT NULL,
    t3ver_state tinyint(4) DEFAULT '0' NOT NULL,
    t3ver_stage int(11) DEFAULT '0' NOT NULL,
    t3ver_count int(11) DEFAULT '0' NOT NULL,
    t3ver_tstamp int(11) DEFAULT '0' NOT NULL,
    t3ver_move_id int(11) DEFAULT '0' NOT NULL,
    tstamp int(11) unsigned DEFAULT '0' NOT NULL,
    crdate int(11) unsigned DEFAULT '0' NOT NULL,
    cruser_id int(11) unsigned DEFAULT '0' NOT NULL,
    deleted tinyint(4) unsigned DEFAULT '0' NOT NULL,
    hidden tinyint(4) unsigned DEFAULT '0' NOT NULL,
    starttime int(11) unsigned DEFAULT '0' NOT NULL,
    endtime int(11) unsigned DEFAULT '0' NOT NULL,
    sys_language_uid int(11) DEFAULT '0' NOT NULL,
    l10n_parent int(11) unsigned DEFAULT '0' NOT NULL,
    l10n_diffsource mediumblob,
    tx_wsbootstrapcomponents_carddeckimage int(11) unsigned DEFAULT '0' NOT NULL,
    tx_wsbootstrapcomponents_carddeckheader tinytext,
    tx_wsbootstrapcomponents_carddecktitle tinytext,
    tx_wsbootstrapcomponents_carddecksubtitle tinytext,
    tx_wsbootstrapcomponents_carddeckbodytext text,
    tx_wsbootstrapcomponents_carddeckphone tinytext,
    tx_wsbootstrapcomponents_carddeckfax tinytext,
    tx_wsbootstrapcomponents_carddeckmail tinytext,
    tx_wsbootstrapcomponents_carddeckbuttonlink tinytext,
    tx_wsbootstrapcomponents_carddeckbuttontext tinytext,
    tx_wsbootstrapcomponents_carddeckimagebottom int(11) unsigned DEFAULT '0' NOT NULL,
    tx_wsbootstrapcomponents_carddeckfooter tinytext,
    PRIMARY KEY (uid),
    KEY parent (pid),
    KEY t3ver_oid (t3ver_oid,t3ver_wsid),
    KEY language (l10n_parent,sys_language_uid)
);
CREATE TABLE tx_wsbootstrapcomponents_carousel (
    uid int(11) NOT NULL auto_increment,
    pid int(11) DEFAULT '0' NOT NULL,
    parentid int(11) DEFAULT '0' NOT NULL,
    parenttable varchar(255) DEFAULT '' NOT NULL,
    sorting int(11) unsigned DEFAULT '0' NOT NULL,
    t3ver_oid int(11) unsigned DEFAULT '0' NOT NULL,
    t3ver_id int(11) DEFAULT '0' NOT NULL,
    t3ver_wsid int(11) DEFAULT '0' NOT NULL,
    t3ver_label varchar(255) DEFAULT '' NOT NULL,
    t3ver_state tinyint(4) DEFAULT '0' NOT NULL,
    t3ver_stage int(11) DEFAULT '0' NOT NULL,
    t3ver_count int(11) DEFAULT '0' NOT NULL,
    t3ver_tstamp int(11) DEFAULT '0' NOT NULL,
    t3ver_move_id int(11) DEFAULT '0' NOT NULL,
    tstamp int(11) unsigned DEFAULT '0' NOT NULL,
    crdate int(11) unsigned DEFAULT '0' NOT NULL,
    cruser_id int(11) unsigned DEFAULT '0' NOT NULL,
    deleted tinyint(4) unsigned DEFAULT '0' NOT NULL,
    hidden tinyint(4) unsigned DEFAULT '0' NOT NULL,
    starttime int(11) unsigned DEFAULT '0' NOT NULL,
    endtime int(11) unsigned DEFAULT '0' NOT NULL,
    sys_language_uid int(11) DEFAULT '0' NOT NULL,
    l10n_parent int(11) unsigned DEFAULT '0' NOT NULL,
    l10n_diffsource mediumblob,
    tx_wsbootstrapcomponents_carouselimage int(11) unsigned DEFAULT '0' NOT NULL,
    tx_wsbootstrapcomponents_carouselheader tinytext,
    tx_wsbootstrapcomponents_carouseltrailer tinytext,
    tx_wsbootstrapcomponents_carouseltextalign tinytext,
    tx_wsbootstrapcomponents_carouselcolor tinytext,
    tx_wsbootstrapcomponents_carousellink tinytext,
    tx_wsbootstrapcomponents_carouselbuttoncolor tinytext,
    tx_wsbootstrapcomponents_carousellinktext tinytext,
    tx_wsbootstrapcomponents_carousellargetext int(11) DEFAULT '0' NOT NULL,
    PRIMARY KEY (uid),
    KEY parent (pid),
    KEY t3ver_oid (t3ver_oid,t3ver_wsid),
    KEY language (l10n_parent,sys_language_uid)
);
